### ISSUE TITLE
gama_client.js doesn't work anymore on Gama 1.9.3

### ISSUE THREAD

**Issue by agrignard** [gama-platform/gama.clients#11]
To reproduce

1. Run Gama Server
2. In gama_client.js update your var ABSOLUTE_PATH_TO_GAMA
3. Open Javascript/index.html

Working with Gama 1.9.1 and 1.9.2 but not with 1.9.3 with the following error message when running:
```UD_ReAgent_ABM/ReAgent/models/Gratte_Ciel_Demo.gaml```

`````
java.lang.NullPointerException: Cannot invoke "msi.gama.metamodel.topology.ITopology.directionInDegreesTo(msi.gama.runtime.IScope, msi.gama.metamodel.shape.IShape, msi.gama.metamodel.shape.IShape)" because the return value of "msi.gama.runtime.IScope.getTopology()" is null
`````
And the following one when running ```'gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml'```

````
/Users/arno/Projects/GitHub/gama/msi.gama.models/models/Tutorials/Road Traffic/models/Model 05.gaml model is being compiled...
Model not compiled because of the following compilation errors: 
This definition of shape supersedes the one in built-in species agent
This definition of step supersedes the one in built-in species model
This definition of shape supersedes the one in built-in species agent
This definition of step supersedes the one in built-in species model
'time / #h' will be  truncated to int.
Unknown operator: goto
Unknown operator: goto
````
